### ISSUE TITLE
Add new coordinate system

### ISSUE THREAD

**Issue by gnssgrid** [loesler/applied-geodesy#169]
Hi Micha
Is it possible to add new CRS in modul for coordinate conversion?

Regards
Dzevad

**Comment by loesler** [comment]
Hello Dzevad,

what kind of CRS and how is it defined?

kind regrads 
Micha

**Comment by gnssgrid** [comment]
It is three zones of MGI for Bosnia (Old Datum). 
First CRS can be named as DKSBiH_GK5:
Ref. elipsoid: Bessel 1841, Projection is Gauss-Krueger 5th zone: Central meridian 15°, scale factor is 0.9999, zone width is 3°
First CRS can be named as DKSBiH_GK6:
Ref. elipsoid: Bessel 1841, Projection is Gauss-Krueger 6th zone: Central meridian 18°, scale factor is 0.9999, zone width is 3°
First CRS can be named as DKSBiH_GK7:
Ref. elipsoid: Bessel 1841, Projection is Gauss-Krueger 7th zone: Central meridian 21°, scale factor is 0.9999, zone width is 3°

New CRS is BH_ETRS89:
Ref. elipsoid: GRS80, Projection is Transverse Mercator: Central meridian 18°, scale factor is 0.9999, zone width is 6°

**Comment by loesler** [comment]
Hello,

it is just the definition of the projection. How to transform from e.g. DKSBiH to BH_ETRS89? Are there specific parameters of a Helmert-Transformation?

/Micha

**Comment by gnssgrid** [comment]
hi Micha
No there is no Helmert-transformation parameters, but I have Ntv2 file for transformation. Unfortunately I can't share it know, until I get permission. I hope that it will be free available soon.

**Comment by loesler** [comment]
Hello,

the Gauß-Krüger System in Germany coded the zone number at the east-coordinate, i.e.:

`y + 500000.0 + zone*1000000.0`

Is there some similar definition for the Bosnia system?

(btw.: the scale is always(!) 0.9999 for GK and UTM?)

**Comment by gnssgrid** [comment]
yes, it is the same in Bosnia. And scale is 0.9999, so the formula for east and north is (for example GK 5 zone):
y (GK5)=y*0.9999+500000+5*1000000
x (GK5)=x*0.9999

**Comment by loesler** [comment]
Hi,

okay, so the zone number (e.g. 5, 7, and 7) can be automatically extracted from the coordinates (and you don't need three options (e.g. DKSBiH_GK5, DKSBiH_GK6, and DKSBiH_GK7)

The scale for UTM is 0.9999, too (and not 0.999**6**)? Is it really right?

/Micha

**Comment by gnssgrid** [comment]
Yes scale for UTM is 0.9999 and east north coordinates are computed without zone number e.g.
E=e*0.9999+500000
N=n*0.9999

**Comment by loesler** [comment]
Hi Dzevad,

to avoid an erroneous implementation. Can you provide a source for the UTM scale definition? I took a look to the EPSG [website](https://epsg.io/) but could't figured out the 0.9999 for [UTM](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system). 

I also found some [transformation parameters](http://webhelp.infovista.com/Planet/62/Subsystems/MapInfo/Content/pro_help/coordinatesdatums/seveneightparameterdatums.html) that can be used as an alternative to the NTv2 grid. Can you also provide some examples for validation?

/Micha

**Comment by loesler** [comment]
... and, furthermore, can you provide the source system and the target system name of the NTv2 file, i.e., SYSTEM_F and SYSTEM_T. I use a regular expression to _identify_ pre-defined systems.

**Comment by gnssgrid** [comment]
Hi Micha

System from is BH_ETRS89. You can put just ETRS89. System to is DKSBiH.
Unfortunately there is no EPSG code for our new system. Projection is
defined ad TM with central meridian 18deg and scale 0.9999 and false east
as 500000
I will try to find utm with 0.9999 scale in the epsg database.
I finished translation to Bosnian lang, but I must check it before
publishing.


pet, 8. jan 2021. 17:21 pošiljalac Michael Loesler <notifications@github.com>
je napisao:

**Comment by loesler** [comment]
Okay, due to the scale 0.9999 in UTM, I have to change some more function but this is not a problem - I just wanted to make sure the right scale. I will provide a snapshot of a modified version soon. Maybe, you can provide some example points in BH_ETRS89 and DKSBiH.

**Comment by gnssgrid** [comment]
Hi Micha

here are test data with transformation parameters (first sheet is test data
and second is transformation parameters).
The coordinates are real one, and if you transform points with provided
parameters there will be difference about few decimeters.

Regards
Dzevad Krdzalic
Tel: +387 61 617 305


pet, 8. sij 2021. u 18:10 Michael Loesler <notifications@github.com>
napisao je:

**Comment by loesler** [comment]
Hi Dzevad,

please note that you wrote to the notification email address from github (notifications@github.com) and not to my personal one.  Your email is transferred to the your github ticket. So, attachments are removed.

/Micha

**Comment by loesler** [comment]
For traceability: Dzevad tested a snapshot of a new version of GeoTra successfully. This version will be part of the next release.
